apiVersion: 1
datasources:
  - name: InfluxDB(GraphQL)
    type: influxdb
    access: proxy
    database: $V1_DB_NAME
    user: $V1_AUTH_USERNAME
    secureJsonData:
      password: $V1_AUTH_PASSWORD
    url: http://fdn.caps.in.tum.de:8086
    isDefault: true
    editable: true

  - name: InfluxDB(Flux)
    version: 2
    type: influxdb
    access: proxy
    url: http://fdn.caps.in.tum.de:8086
    editable: true
    jsonData:
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
      httpMode: POST
      organization: $DOCKER_INFLUXDB_INIT_ORG
      version: Flux
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN